<?php

return array(
        'Elements'   => array(
                'Buttons' => '?page=element/buttons',
                'Panels'  => '?page=element/panels'
        ),
        'Containers' => array(
                'Card'     => '?page=container/card',
                'Grid'     => '?page=container/grid',
                'Download' => '?page=container/download',
                'Sitemap'  => '?page=container/sitemap',
        ),
        'Test'       => array(
                'Collections' => '?page=collection',
                'Regexp'      => '?page=regexp'
        )
);
