<?php

return array(
        'Elements'   => array(
                'Buttons' => '?page=element/buttons',
                'Panels'  => '?page=element/panels'
        ),
        'Containers' => array(
                'Card'     => '?page=container/card',
                'Cell'     => '?page=container/cell',
                'Grid'     => '?page=container/grid',
                'Download' => '?page=container/download',
                'Sitemap'  => '?page=container/sitemap',
        ),
        'Transform'  => array(
                'Paragon'   => '?page=transform/paragon',
                'Native'    => '?page=transform/native',
                'Bootstrap' => '?page=transform/bootstrap'
        ),
        'Properties' => array(
                'Color'     => '?page=properties/color',
                'Container' => '?page=properties/container',
                'Display'   => '?page=properties/display',
                'Effect'    => '?page=properties/effect',
                'Padding'   => '?page=properties/padding',
                'Shadow'    => '?page=properties/card',
        ),
        'Test'       => array(
                'Collections' => '?page=collection',
                'Regexp'      => '?page=regexp'
        )
);
