<?php

namespace UUP\Web\Component\Collection;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-09-27 at 02:09:48.
 */
class CollectionTest extends \PHPUnit_Framework_TestCase
{

        /**
         * @var Collection
         */
        protected $object;

        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp()
        {
                $this->object = new Collection('|', '@', "'", 'name');
        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown()
        {
                
        }

        /**
         * @covers UUP\Web\Component\Collection\Collection::__set
         * @todo   Implement test__set().
         */
        public function test__set()
        {
                $this->object->name = "value1|value2";
                
                $expect = 2;
                $actual = $this->object->count();
                self::assertEquals($expect, $actual);
                
                $expect = "value1|value2";
                $actual = $this->object->join();
                self::assertEquals($expect, $actual);
        }

        /**
         * @covers UUP\Web\Component\Collection\Collection::__toString
         * @todo   Implement test__toString().
         */
        public function test__toString()
        {
        }

        /**
         * @covers UUP\Web\Component\Collection\Collection::add
         * @todo   Implement testAdd().
         */
        public function testAdd()
        {
                $this->object->add("v1|v2");
                $expect = "2";
        }

        /**
         * @covers UUP\Web\Component\Collection\Collection::set
         * @todo   Implement testSet().
         */
        public function testSet()
        {
        }

        /**
         * @covers UUP\Web\Component\Collection\Collection::remove
         * @todo   Implement testRemove().
         */
        public function testRemove()
        {
        }

        /**
         * @covers UUP\Web\Component\Collection\Collection::join
         * @todo   Implement testJoin().
         */
        public function testJoin()
        {
        }

        /**
         * @covers UUP\Web\Component\Collection\Collection::count
         * @todo   Implement testCount().
         */
        public function testCount()
        {
        }

        /**
         * @covers UUP\Web\Component\Collection\Collection::clear
         * @todo   Implement testClear().
         */
        public function testClear()
        {
        }

}
