<?php

namespace UUP\Web\Component\Collection;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-10-02 at 14:30:34.
 */
class PropertiesTest extends \PHPUnit_Framework_TestCase
{

        /**
         * @var Properties
         */
        protected $object;

        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp()
        {
                $this->object = new Properties();
        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown()
        {
                
        }

        /**
         * Test prefixed properties.
         */
        public function testPrefixed()
        {
                $expect = 'green';
                $this->object->color->back = $expect;
                $actual = $this->object->color->back;
                self::assertNotNull($actual);
                self::assertEquals($actual, $expect);
                
                $expect = 1;
                $actual = $this->object->count();
                self::assertNotNull($actual);
                self::assertEquals($actual, $expect);
                
                $expect = 'green';
                $actual = $this->object->get('color-back');
                self::assertNotNull($actual);
                self::assertEquals($actual, $expect);
        }

}
